# Generated by Django 3.1.7 on 2021-04-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_hruser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=20)),
                ('payout', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.hruser')),
            ],
        ),
    ]
