# Generated by Django 3.1.7 on 2021-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20210404_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
